# ======================================
# General configuration settings
# ======================================
seed: null        # set to None (null) or a value for deterministic reproducibility

use_wandb: true   # set to null if no wandb should be used

# WanDB Logging
wandb:
  project: "MPL-TMT-Combined_LRO-CE_final"
  entity: "nids-inm4"       # Wandb entity name (user/organization)
  log_freq: 1               # Frequency (in epochs) of logging metrics during training
  notes: 'testing'          # put some notes here


# ======================================
# Data
# ======================================
data:
  path: "./data/"
  # filenames: ['ExecTMTA.csv','ExecTMTB.csv']                            # contains NO subject IDs
  filenames: ['ExecPapTMTA.xlsx', 'ExecPapTMTB.xlsx']                     # contains subject IDs
  drop_columns: ['TIV', 'Age', 'Gender', 'Geschlecht', 'TMT_A', 'TMT_B']  # possible column names to drop
  do_norm: true
  norm_axis:  0        # 0 (default) => apply normalisation across columns
  n_comp_pca: 0        # 0 (default) => apply PCA decomposition if n_comp > 0
  n_comp_ica: 0        # 0 (default) => apply ICA decomposition if n_comp > 0
  ratio_val: 0.2       # 0.2 (default) => ratio of test split


# ======================================
# cross-validation
# ======================================
train:
  mode: "LRO"  # Learning mode: "LRO" for leave-one-run-out cross-validation, "LSO" for leave-subject-out cross-validation

  # n_repeat: 1      # for testing
  # n_repeat: 5      # for testing
  n_repeat: 10
  # n_repeat: 50
  # n_repeat: 100

  max_epochs:  100    # Number of Epochs (100 default for CE)
  batch_size: -1      # Batch size for training. Set to -1 (default) for using all data


# ======================================
# data augmentation
# ======================================
augmentation:
  add_chan: 0        # 0 (default). Set to >0 to add additional channels with permuted columns
  crop: 0            # 0 (default)  Set to >0 to crop row elements randomly to use a less features
  permute: null      # null (default). Set to true to permute the order of the features



# ======================================
# Model parameters
# ======================================
model:
  loss_type: "CrossEntropy"   # only LRO mode is possible!
  dim_out:  32                # 32 (default). Size of output layer
  lr:  0.2                   # 0.2 (default). Warm-Up LR value
  dropout:  0.0               # 0 (default). Dropout ratio
  weight_decay:  0.0          # 0 (default). weight decay
  label_smoothing:  0.0       # 0 (default). label smoothing

# Trainer configuration
trainer:
  device: 1
  accelerator: 'auto'
  num_workers:  0
  gradient_clip_val: 1.0        # 1.0 (default). Clip gradients to stabilize updates or set to null

# ======================================
# SHAP Analysis
# ======================================
shap:
  explainer: 'PermutationExplainer'  # 'DeepExplainer', 'PermutationExplainer', or 'KernelExplainer'
  nsamples: 100                 # Used for KernelExplainer
  max_evals: 5000               # Used for PermutationExplainer
  batch_size: 50                # Batch size for explainers
